<?xml version="1.0" encoding="UTF-8"?>
<!--- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Legal Notices

S.W.I.F.T. SC © 2025. All rights reserved.

This schema is a component of MyStandards, the Swift collaborative Web application used to manage
standards definitions and industry usage.

This is a licensed product, which may only be used and distributed in accordance with MyStandards License
Terms as specified in MyStandards Service Description and the related Terms of Use.

Unless otherwise agreed in writing with S.W.I.F.T. SC, the user has no right to:
 - authorise external end users to use this component for other purposes than their internal use.
 - remove, alter, cover, obfuscate or cancel from view any copyright or other proprietary rights notices appearing in this physical medium.
 - re-sell or authorise another party e.g. software and service providers, to re-sell this component.

This component is provided 'AS IS'. Swift does not give and excludes any express or implied warranties
with respect to this component such as but not limited to any guarantee as to its quality, supply or availability.

Any and all rights, including title, ownership rights, copyright, trademark, patents, and any other intellectual 
property rights of whatever nature in this component will remain the exclusive property of Swift or its 
licensors.

Trademarks and Patents
Swift is the trade name of S.W.I.F.T. SC.
The following are registered trademarks of Swift: 3SKey, Innotribe, MyStandards, Sibos, Swift, SwiftNet, Swift Institute, the Standards Forum logo, the Swiftlogo, Swift GPI with logo, the Swift GPI logo, and UETR.
Other product, service, or company names in this publication are trade names, trademarks, or registered trademarks of their respective owners.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Group: HKTR
Collection: HKTR AIDG (ISO 20022) V1.0.3 [Published on 8 August 2025]
Usage Guideline: head.001.001.04_HKMAUG
Base Message: head.001.001.04
Date of publication: 01 August 2025
URL: https://www2.swift.com/mystandards/#/mp/mx/_M6OZ0G6uEfCJopnN3Dt3Iw/_M6Rdlm6uEfCJopnN3Dt3Iw
Description: The Business Layer deals with Business Messages. The behaviour of the Business Messages is fully described by the Business Transaction and the structure of the Business Messages is fully described by the Message Definitions and related Message Rules, Rules and Market Practices. All of which are registered in the ISO 20022 Repository.
A single new Business Message (with its accompagnying business application header) is created - by the sending MessagingEndpoint - for each business event; that is each interaction in a Business Transaction. A Business Message adheres to the following principles:
" A Business Message (and its business application header) must not contain information about the Message Transport System or the mechanics or mechanism of message sending, transportation, or receipt. 
" A Business Message must be comprehensible outside of the context of the Transport Message. That is the Business Message must not require knowledge of the Transport Message to be understood.
" A Business Message may contain headers, footers, and envelopes that are meaningful for the business. When present, they are treated as any other message content, which means that they are considered part of the Message Definition of the Business Message and as such will be part of the ISO 20022 Repository.
" A Business Message refers to Business Actors by their Name. Each instance of a Business Actor has one Name. The Business Actor must not be referred to in the Transport Layer.
Specific usage of this BusinessMessageHeader may be defined by the relevant SEG.
Generated by the MyStandards web platform [https://www.swift.com/mystandards] on 2025-08-01T08:05:38Z
-->
<!---->
<xs:schema xmlns="urn:iso:std:iso:20022:tech:xsd:head.001.001.04" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="urn:iso:std:iso:20022:tech:xsd:head.001.001.04">
    <xs:element name="AppHdr" type="BusinessApplicationHeaderV04"/>
    <xs:complexType name="BusinessApplicationHeaderV04">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">BusinessApplicationHeaderV04</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">The Business Layer deals with Business Messages. The behaviour of the Business Messages is fully described by the Business Transaction and the structure of the Business Messages is fully described by the Message Definitions and related Message Rules, Rules and Market Practices. All of which are registered in the ISO 20022 Repository.&#13;
A single new Business Message (with its accompagnying business application header) is created - by the sending MessagingEndpoint - for each business event; that is each interaction in a Business Transaction. A Business Message adheres to the following principles:&#13;
" A Business Message (and its business application header) must not contain information about the Message Transport System or the mechanics or mechanism of message sending, transportation, or receipt. &#13;
" A Business Message must be comprehensible outside of the context of the Transport Message. That is the Business Message must not require knowledge of the Transport Message to be understood.&#13;
" A Business Message may contain headers, footers, and envelopes that are meaningful for the business. When present, they are treated as any other message content, which means that they are considered part of the Message Definition of the Business Message and as such will be part of the ISO 20022 Repository.&#13;
" A Business Message refers to Business Actors by their Name. Each instance of a Business Actor has one Name. The Business Actor must not be referred to in the Transport Layer.&#13;
Specific usage of this BusinessMessageHeader may be defined by the relevant SEG.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Fr" type="Party51Choice__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">From</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">The sending MessagingEndpoint that has created this Business Message for the receiving MessagingEndpoint that will process this Business Message.&#13;
&#13;
Note	the sending MessagingEndpoint might be different from the sending address potentially contained in the transport header (as defined in the transport layer).</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="To" type="Party51Choice__2">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">To</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">The MessagingEndpoint designated by the sending MessagingEndpoint to be the recipient who will ultimately process this Business Message.&#13;
&#13;
Note the receiving MessagingEndpoint might be different from the receiving address potentially contained in the transport header (as defined in the transport layer).</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="BizMsgIdr" type="Max35Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">BusinessMessageIdentifier</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unambiguously identifies the Business Message to the MessagingEndpoint that has created the Business Message.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="MsgDefIdr" type="Max35Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">MessageDefinitionIdentifier</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">The Message Definition Identifier of the Business Message instance with which this Business Application Header instance is associated.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="CreDt" type="HKTRDateTime">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">CreationDate</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Date and time when this Business Message (header) was created.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="GenericOrganisationIdentification3__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">GenericOrganisationIdentification3__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Information related to an identification of an organisation.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Id" type="Max20Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Identification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Identification assigned by an institution.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="HKTRDateTime">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">HKTRDateTime</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Expressed in UTC time format (YYYY-MM-DDThh:mm:ssZ)</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:dateTime"/>
    </xs:simpleType>
    <xs:simpleType name="LEIIdentifier">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">LEIIdentifier</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Legal Entity Identifier is a code allocated to a party as described in ISO 17442 "Financial Services - Legal Entity Identifier (LEI)".</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z0-9]{18,18}[0-9]{2,2}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Max20Text">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">Max20Text</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies a character string with a maximum length of 20 characters.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="20"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Max35Text">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">Max35Text</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies a character string with a maximum length of 35 characters.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="35"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="OrganisationIdentification39__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">OrganisationIdentification39__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Unique and unambiguous way to identify an organisation.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element maxOccurs="1" minOccurs="0" name="LEI" type="LEIIdentifier">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">LEI</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Legal entity identification as an alternate identification for a party.</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="Othr" type="GenericOrganisationIdentification3__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Other</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique identification of an organisation, as assigned by an institution, using an identification scheme.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="OrganisationIdentification39__2">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">OrganisationIdentification39__2</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Unique and unambiguous way to identify an organisation.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Othr" type="GenericOrganisationIdentification3__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Other</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique identification of an organisation, as assigned by an institution, using an identification scheme.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Party51Choice__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">Party51Choice__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Identification of a person, an organisation or a financial institution.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="OrgId" type="PartyIdentification272__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">OrganisationIdentification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Identification of a person or an organisation.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="Party51Choice__2">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">Party51Choice__2</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Identification of a person, an organisation or a financial institution.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="OrgId" type="PartyIdentification272__2">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">OrganisationIdentification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Identification of a person or an organisation.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="Party52Choice__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">Party52Choice__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies the identification of a person or an organisation.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="OrgId" type="OrganisationIdentification39__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">OrganisationIdentification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique and unambiguous way to identify an organisation.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="Party52Choice__2">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">Party52Choice__2</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies the identification of a person or an organisation.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="OrgId" type="OrganisationIdentification39__2">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">OrganisationIdentification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique and unambiguous way to identify an organisation.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="PartyIdentification272__1">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">PartyIdentification272__1</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies the identification of a person or an organisation.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Id" type="Party52Choice__1">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Identification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique and unambiguous identification of a party.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="PartyIdentification272__2">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">PartyIdentification272__2</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies the identification of a person or an organisation.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Id" type="Party52Choice__2">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Identification</xs:documentation>
                    <xs:documentation source="Definition" xml:lang="EN">Unique and unambiguous identification of a party.</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>
