<?xml version="1.0" encoding="UTF-8"?>
<!--- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Legal Notices

S.W.I.F.T. SC © 2025. All rights reserved.

This schema is a component of MyStandards, the Swift collaborative Web application used to manage
standards definitions and industry usage.

This is a licensed product, which may only be used and distributed in accordance with MyStandards License
Terms as specified in MyStandards Service Description and the related Terms of Use.

Unless otherwise agreed in writing with S.W.I.F.T. SC, the user has no right to:
 - authorise external end users to use this component for other purposes than their internal use.
 - remove, alter, cover, obfuscate or cancel from view any copyright or other proprietary rights notices appearing in this physical medium.
 - re-sell or authorise another party e.g. software and service providers, to re-sell this component.

This component is provided 'AS IS'. Swift does not give and excludes any express or implied warranties
with respect to this component such as but not limited to any guarantee as to its quality, supply or availability.

Any and all rights, including title, ownership rights, copyright, trademark, patents, and any other intellectual 
property rights of whatever nature in this component will remain the exclusive property of Swift or its 
licensors.

Trademarks and Patents
Swift is the trade name of S.W.I.F.T. SC.
The following are registered trademarks of Swift: 3SKey, Innotribe, MyStandards, Sibos, Swift, SwiftNet, Swift Institute, the Standards Forum logo, the Swiftlogo, Swift GPI with logo, the Swift GPI logo, and UETR.
Other product, service, or company names in this publication are trade names, trademarks, or registered trademarks of their respective owners.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Message name: auth.030.001.04
URL: https://www2.swift.com/mystandards/#/mx/auth.030.001.04
Generated by the MyStandards web platform [https://www.swift.com/mystandards] on 2025-08-06T11:15:02Z
ISO 20022 version : 2004
-->
<!---->
<xs:schema xmlns="auth.030.001.04_HKMAUG_DATTAR/extension" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="auth.030.001.04_HKMAUG_DATTAR/extension">
    <xs:element name="Document" type="Document"/>
    <xs:complexType name="Document">
        <xs:sequence>
            <xs:element name="HktrExtension" type="HktrExtension"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="HKTRMax19Text">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">HKTRMax19Text</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies a character string with a maximum length of 19 characters.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="19"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="HKTRMax255Text">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">HKTRMax255Text</xs:documentation>
            <xs:documentation source="Definition" xml:lang="EN">Specifies a character string with a maximum length of 255 characters.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="255"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="HktrExtension">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">HktrExtension</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Remarks" type="Remarks">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Remarks</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Remarks">
        <xs:annotation>
            <xs:documentation source="Name" xml:lang="EN">Remarks</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element maxOccurs="1" minOccurs="0" name="Remarks" type="HKTRMax19Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Remarks</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="Remarks1" type="HKTRMax255Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Remarks1</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="Remarks2" type="HKTRMax255Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Remarks2</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="Remarks3" type="HKTRMax255Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Remarks3</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="Remarks4" type="HKTRMax255Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Remarks4</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="Remarks5" type="HKTRMax255Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Remarks5</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="Remarks6" type="HKTRMax255Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Remarks6</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="Remarks7" type="HKTRMax255Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Remarks7</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="Remarks8" type="HKTRMax255Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Remarks8</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="Remarks9" type="HKTRMax255Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Remarks9</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="Remarks10" type="HKTRMax255Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Remarks10</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="Remarks11" type="HKTRMax255Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Remarks11</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="Remarks12" type="HKTRMax255Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Remarks12</xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element maxOccurs="1" minOccurs="0" name="Remarks13" type="HKTRMax255Text">
                <xs:annotation>
                    <xs:documentation source="Name" xml:lang="EN">Remarks13</xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>
